services:

  postgres:
    image: postgres:16-alpine
    container_name: payments-postgres
    env_file: [.env]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [payments-net]

  redis:
    image: redis:7-alpine
    container_name: payments-redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks: [payments-net]

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: payments-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [payments-net]

  api:
    build: .
    container_name: payments-api
    env_file: [.env]
    environment:
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      postgres: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}
      redis: {condition: service_healthy}
    command: ["python", "manage.py", "start-api"]
    networks: [payments-net]

  consumer:
    build: .
    container_name: payments-consumer
    env_file: [.env]
    environment:
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}
      redis: {condition: service_healthy}
      api: {condition: service_started}
    command: ["python", "manage.py", "start-consumer"]
    networks: [payments-net]

  outbox-publisher:
    build: .
    container_name: payments-outbox-publisher
    env_file: [.env]
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}
      api: {condition: service_started}
    command: ["python", "manage.py", "start-outbox-publisher"]
    networks: [payments-net]

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  payments-net:
    driver: bridge
